package com.invoice.contratista.utils

const val EMAIL_CANNOT_EQUALS_PASSWORD = "Email and password cannot be the same"
const val PASSWORD_NOT_MATCH = "Password do not match"
const val UNEXPECTED_ERROR = "Unexpected error"
const val HIGH = "high"
const val REQUIRED = "Required"
const val EVENT_DATA = "Event data"
const val NOTE = "Note"
const val ENTER_ = "Enter "
const val ENTER_NOTE = "$ENTER_$NOTE please"
const val EDIT_NOTE = "edit_note"
const val LEGAL_NAME = "Legal name"
const val CUSTOMER_DATA = "Customer data"
const val TAX_IDENTIFICATION = "Tax identification"
const val FISCAL_REGIME = "Fiscal regime"
const val EMAIL = "Email"
const val PHONE = "Phone"
const val ADDRESS = "Address"
const val EXTERIOR = "Exterior"
const val INTERIOR = "Interior"
const val ADD_BUDGET = "Add budget"
const val BUDGET = "Budget"
const val DATE = "Date"
const val STATUS = "Status"